name: 03 - Runners de workflow
on:
  push:
jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps: 
      - name: "SO Ubuntu"
        run: |
        echo "Este trabajo se ejecuta en un Runner de Ubuntu"
        echo $RUNNER_OS
    windows-echo:
    runs-on: windows-latest
    steps: 
      - name: "SO Windows"
        run: |
        echo "Este trabajo se ejecuta en un Runner de Windows"
        echo $RUNNER_OS
    macos-echo:
    runs-on: macos-latest
    steps: 
      - name: "SO macOS"
        run: |
        echo "Este trabajo se ejecuta en un Runner de macOS"
        echo $RUNNER_OS
        
  