name: 07 - Contexts
run-name: 07 - Contexts | DEBUG - ${{ inputs.debug }}

on:
  push:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        type: boolean
        default: false

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env: 
      MY_VAR_TWO: "Hello, I'm a second variable from GitHub Actions!"
    steps:
      - name: Show GitHub Context
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
      
      - name: Retrieve Variable
        run: echo "MY_VAR = ${{ vars.MY_VAR }}"

      - name: Print my second var
        run: echo "MY_VAR_TWO = $MY_VAR_TWO"

      - name: Check debug input
        run: | 
            if [ "${{ inputs.debug }}" = "true" ]; then
                echo "Debug mode is ON"
                echo "Debug info: Event ${{ github.event_name }}, Actor ${{ github.actor }}"
            else
                echo "Debug mode is OFF"
            fi


